name: Validating terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-init:
    name: terraform-init
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.6 # Change this to your desired Terraform version
    - name: setting up aws config
      run: export ${{secrets.AWS_ACCESS_ID}}

    - name: Initialize Terraform
      run: cd provisioning/dev/cluster && terraform init

  terraform-validate:
    name: terraform-validate
    runs-on: ubuntu-latest
    needs: terraform-init

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.6 # Change this to your desired Terraform version

    - name: Change to Terraform directory
      run: cd provisioning/dev/cluster

    - name: Initialize Terraform
      run: terraform init
    
    - name: terraform validate
      run: terraform validate
